name: Android CI

on:
  repository_dispatch:
    types:
      - build_trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Prepare environment
      run: |
        echo "Prepare environment based on android-ci..."
        chmod +x make.sh
        chmod +x gradlew

    - name: Run make script
      env:
        URL: ${{ github.event.client_payload.sdkUrl }}
        APP_ID: ${{ github.event.client_payload.appId }}
        APK_PACKAGE_NAME: ${{ github.event.client_payload.apkPackageName }}
        SDK_PACKAGE_NAME: ${{ github.event.client_payload.sdkPackageName }}
        RUN_ID: ${{ github.event.client_payload.uuid }}
      run: |
        echo "Running make.sh script with parameters..."
        echo "ID: $RUN_ID"
        ./make.sh "$URL" "$APP_ID" "$APK_PACKAGE_NAME" "$SDK_PACKAGE_NAME"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: app/build/outputs/apk/release/app-release.apk

    - name: Cleanup
      run: |
        echo "Cleanup any build artifacts..."
        # Add any cleanup steps here

    - name: Post build results
      if: ${{ failure() }}
      run: |
        echo "Build failed..."
        # Add any steps to handle build failure here
